package com.revature.exceptions;

public class FirstException {
	public static void main(String[] args) {
		int x = 20;
		int y = 0;
		try {
		int  result = x/y;
		}
		System.out.println("Result= " + result);
		System.out.println("Done . . . . . . . ");
	}

}
